### PR TITLE
Complete rewrite using REST

### LINKED ISSUE #1: [Bug] Can't connect to ISPConfig 3
### Describe the bug

When trying to establish a connection, I see an error "Server_Exception::__construct(): Argument FOSSBilling/FOSSBilling#2 ($variables) must be of type ?array, int given, called in /var/www/example.com/library/Server/Manager/Ispconfig3.php on line 541 (9998)"

### How to reproduce

1. ISPConfig 3 installed on Debian 11
2. In FossBilling go to "Configuration" => "Hosting plans and servers" => "New Server" and enter all data
3. After creation try to modify server data or click button "Test connection"

### Expected behavior

Tested the connection with HestiaCP in the same way - everything is OK

### Screenshots

_No response_

### FOSSBilling version

v0.3.0 stable

### Module version

_No response_

### Device

_No response_

### Information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jsonkenyon**
This update rewrites the entire module and drops the SOAP API, and exchange for the REST API.  Closes #1

### CODE REVIEW

**Comment by concienciadesventurada** [comment]
hi, FOSSBilling team!

I wanted to know if this can be implemented, this service has been unmaintained for the past few months, plain soap api in its current state is clunky at best

**Review by BelleNottelling — COMMENTED** [review]
Overall this looks quite good, although I am seeing some items marked as "TODO" and a few very minor formatting issues.

From a code perspective though it's a huge improvement over the previous version.
I don't have an ISPConfig server to test it against, so I'll have to take your word that it works as intended

**Comment by jsonkenyon** [comment]
Todos, all completed and should be good to go.  Let me know if you need a ISPConfig 3 setup, I'll see about getting one setup and provide you details over discord.  

(I've currently have mine running locally on my home lab server, in proxmox)

**Review by BelleNottelling — APPROVED** [review]
LGTM, thank you for rebuilding this!

**Comment by jsonkenyon** [comment]
@BelleNottelling No problem, I'm happy to maintain it also if needed.  There's some things I wanna get done, eg return types, further error handling, etc but for now the goal was to just get it working.  Now that it does that I can focus on other things with it, I'm also still searching the api docs but it doesn't seem ISPConfig has an api endpoint for changing plan features.

**Comment by BelleNottelling** [comment]
> @BelleNottelling No problem, I'm happy to maintain it also if needed.  There's some things I wanna get done, eg return types, further error handling, etc but for now the goal was to just get it working.  Now that it does that I can focus on other things with it, I'm also still searching the api docs but it doesn't seem ISPConfig has an api endpoint for changing plan features. 

Sounds great!

I'm going to give about a week so other contributiors a chance to review the PR as well, if no objections are mentioned before then, I'll merge this, update some info on the repo, link to it on our website, and announce it's fixed status via our discord & forum.

That's again for the contribution!

**Comment by BelleNottelling** [comment]
@jsonkenyon Thank you again for the rewrite and for offering to help maintain this integration!

I've merged your PR and published a release with your rewritten version.
On top of that, I have sent you an invite to this repository as a maintainer so that you'll be able to help triage issues & have a generally smoother process maintaining it.

Cheers!

**Pull request merged**
